# Generated by Django 3.0.5 on 2025-03-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20250324_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='student_background',
            field=models.CharField(blank=True, choices=[('orphaned', 'Orphaned or abandoned children'), ('single_parent', 'Children from single-parent households'), ('low_income', 'Students from low-income families')], max_length=20, null=True),
        ),
    ]
