# Generated by Django 5.1.7 on 2025-03-30 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
    ]
