# Generated by Django 3.0.5 on 2025-03-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20210213_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blooddonate',
            name='bloodgroup',
        ),
        migrations.RemoveField(
            model_name='blooddonate',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='bloodgroup',
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='donor',
            name='max_donation_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='donor',
            name='educational_interests',
            field=models.ManyToManyField(blank=True, to='donor.EducationalInterest'),
        ),
        migrations.AddField(
            model_name='donor',
            name='specific_needs',
            field=models.ManyToManyField(blank=True, to='donor.SpecificNeed'),
        ),
        migrations.AddField(
            model_name='donor',
            name='student_backgrounds',
            field=models.ManyToManyField(blank=True, to='donor.StudentBackground'),
        ),
    ]
