# Generated by Django 3.0.5 on 2025-03-24 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_auto_20250320_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='educational_interests',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='specific_needs',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='student_backgrounds',
        ),
    ]
