# Generated by Django 3.0.5 on 2025-03-29 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20250326_2315'),
        ('donor', '0004_auto_20250324_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonate',
            name='amount',
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='bloodgroup',
            field=models.CharField(default='A+', max_length=10),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='unit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='PatientRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=40)),
                ('patient_age', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=500)),
                ('bloodgroup', models.CharField(max_length=10)),
                ('unit', models.PositiveIntegerField(default=1)),
                ('date', models.DateField(auto_now=True)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('education', models.CharField(choices=[('PRIMARY', 'Primary School'), ('SECONDARY', 'Secondary School'), ('HIGHER_SECONDARY', 'Higher Secondary'), ('UNDERGRADUATE', 'Undergraduate'), ('GRADUATE', 'Graduate')], default='PRIMARY', max_length=20)),
                ('educational_interest', models.CharField(choices=[('GENERAL', 'General Education'), ('STEM', 'Science & Technology'), ('ARTS', 'Arts & Humanities'), ('COMMERCE', 'Commerce & Business'), ('VOCATIONAL', 'Vocational Training')], default='GENERAL', max_length=20)),
                ('specific_needs', models.CharField(choices=[('NONE', 'None'), ('DISABILITY', 'Disability Support'), ('FINANCIAL', 'Financial Aid'), ('TRANSPORT', 'Transportation'), ('SUPPLIES', 'Educational Supplies')], default='NONE', max_length=20)),
                ('annual_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('donated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('request_by_patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
            ],
        ),
    ]
