# Generated by Django 3.0.5 on 2025-03-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_auto_20250329_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrequest',
            name='contributors_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
