# Generated by Django 3.0.5 on 2025-03-31 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0004_auto_20250331_1850'),
        ('donor', '0006_patientrequest_contributors_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('mathematics', 'Mathematics'), ('science', 'Science'), ('english', 'English'), ('computer_science', 'Computer Science'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('history', 'History'), ('geography', 'Geography'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Brief description of your teaching experience and approach')),
                ('available_date', models.DateField()),
                ('available_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['available_date', 'available_time'],
            },
        ),
        migrations.DeleteModel(
            name='EducationalInterest',
        ),
        migrations.DeleteModel(
            name='SpecificNeed',
        ),
        migrations.DeleteModel(
            name='StudentBackground',
        ),
        migrations.AddField(
            model_name='donor',
            name='age',
            field=models.CharField(default='30', max_length=3),
        ),
        migrations.AddField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(default='A+', max_length=10),
        ),
        migrations.AddField(
            model_name='donor',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='disease',
            field=models.CharField(default='Nothing', max_length=100),
        ),
        migrations.AddField(
            model_name='donor',
            name='educational_interests',
            field=models.ManyToManyField(blank=True, to='preferences.EducationalInterest'),
        ),
        migrations.AddField(
            model_name='donor',
            name='specific_needs',
            field=models.ManyToManyField(blank=True, to='preferences.SpecificNeed'),
        ),
        migrations.AddField(
            model_name='donor',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='donor',
            name='student_backgrounds',
            field=models.ManyToManyField(blank=True, to='preferences.StudentBackground'),
        ),
        migrations.AddField(
            model_name='donor',
            name='unit',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='mentoravailability',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.Donor'),
        ),
    ]
