# Generated by Django 3.0.5 on 2025-03-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_auto_20250331_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoravailability',
            name='teaching_mode',
            field=models.CharField(choices=[('voice_call', 'Voice Call'), ('video_call', 'Video Call'), ('in_person', 'In-Person Meetup')], default='video_call', max_length=20),
        ),
    ]
