# Generated by Django 3.0.5 on 2025-03-31 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_remove_patient_gender'),
        ('donor', '0008_mentoravailability_teaching_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoravailability',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MentorSessionBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Any specific topics or questions for the mentor', null=True)),
                ('mentor_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='donor.MentorAvailability')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_bookings', to='patient.Patient')),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
    ]
