# Generated by Django 3.0.5 on 2025-03-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0009_auto_20250331_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorsessionbooking',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Video call meeting link', null=True),
        ),
        migrations.AddField(
            model_name='mentorsessionbooking',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Patient's phone number for voice calls", max_length=15, null=True),
        ),
    ]
