# Generated by Django 5.1.7 on 2025-04-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0011_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentoravailability',
            options={},
        ),
        migrations.RemoveField(
            model_name='mentoravailability',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mentoravailability',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='mentoravailability',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentoravailability',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentoravailability',
            name='location_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mentoravailability',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mentoravailability',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentoravailability',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mentoravailability',
            name='specialty',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mentoravailability',
            name='teaching_mode',
            field=models.CharField(choices=[('online', 'Online'), ('in_person', 'In Person')], max_length=20),
        ),
    ]
