# Generated by Django 3.0.5 on 2025-03-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_bloodrequest_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='bloodgroup',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='unit',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='recipient_details',
            field=models.CharField(default='Not specified', max_length=200),
        ),
    ]
