# Generated by Django 3.0.5 on 2025-03-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0006_bloodrequest_educational_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='specific_needs',
            field=models.CharField(blank=True, choices=[('tuition', 'Tuition fees'), ('books', 'Books & learning materials'), ('online', 'Online courses & certifications'), ('transport', 'School transportation costs'), ('digital', 'Internet access & digital devices'), ('special', 'Special education support')], max_length=20, null=True),
        ),
    ]
