# Generated by Django 3.0.5 on 2025-03-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0007_bloodrequest_specific_needs'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='annual_income',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
