# Generated by Django 3.0.5 on 2025-03-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0008_bloodrequest_annual_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='education',
            field=models.CharField(blank=True, choices=[('primary', 'Primary Education (1-5)'), ('middle', 'Middle School (6-8)'), ('secondary', 'Secondary Education (9-10)'), ('higher_secondary', 'Higher Secondary (11-12)'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('phd', 'PhD'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
