# Generated by Django 3.0.5 on 2025-03-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0009_bloodrequest_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='contributors_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='donated_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
