# Generated by Django 5.1.7 on 2025-03-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0010_auto_20250330_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='specially_abled',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
    ]
