# Generated by Django 5.1.7 on 2025-03-30 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0012_bloodrequest_gender'),
        ('donor', '0006_patientrequest_contributors_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(max_length=8)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('beneficiary_name', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=200)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.bloodrequest')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.donor')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
