# Generated by Django 3.0.5 on 2025-03-31 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0013_donationtransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonationTransaction',
        ),
    ]
